zephyrproject-rtos/twister

src/twister2/device/native_simulator_adapter.py
src/twister2/exceptions.py
src/twister2/log.py
src/twister2/report/test_plan_plugin.py
src/twister2/report/test_results_plugin.py

Simulation subprocess wasn't terminated properly after timeout (missing arguments in raise subprocess.TimeoutExpired). This PR fixes it. 
Also improving logging configuration (reading configuration from pytest.ini).

Fix timeout subprocess

---

src/twister2/fixtures/log_parser.py
src/twister2/log_parser/harness_log_parser.py
tests/log_parser/data/device_log.txt
tests/log_parser/data/device_log_with_fail.txt
tests/log_parser/data/device_log_with_fail_dynamic_thread.txt
tests/log_parser/log_parser_test.py

When test has tag "ignore_faults", then it should ignore in output error message like "ZEPHYR FATAL ERROR".
As an example of such a test it can be used this one: `tests/kernel/threads/dynamic_thread`. Output from this test is as following:
```
...
===================================================================
START - test_dyn_thread_perms
E: thread 0x20001664 (3) does not have permission on k_sem 0x20007edc
E: permission bitmap
E: 03 00                   |..
E: syscall z_vrfy_k_sem_give failed check: access denied
E: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x00000000
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00000000
E:  xpsr:  0x00000000
E: Faulting instruction address (r15/pc): 0xffffffff
E: >>> ZEPHYR FATAL ERROR 3: Kernel oops on CPU 0
E: Current thread: …
```

log_parser: fix handling of ZEPHYR FATAL ERROR

---

src/twister2/builder/builder_abstract.py
src/twister2/builder/west.py
tests/builder/west_test.py

This PR fixes a build error when there is more than one extra argument passing to west builder.

Fix preparing extra args for west builder

---

src/twister2/log_parser/log_parser_abstract.py
src/twister2/log_parser/ztest_log_parser.py
src/twister2/yaml_test_function.py
tests/log_parser/ztest_log_parser_test.py

Some damaged tests ends without any printed output and in this situation Twister should mark this test as failed. Using default parser state as "PASSED" is risky and can lead to some false negatives cases in the future.
Suitable test for this case was added.

log_parser: change default parser state

---

src/twister2/platform_specification.py

and new type of simulation: native
Reason of changes:
https://github.com/zephyrproject-rtos/zephyr/commit/3e870495f28a21a44c596800e9f734edfa13aeaf
https://github.com/zephyrproject-rtos/zephyr/commit/dae4720703164a667d141e9e5da87c04c8c18777
Signed-off-by: Grzegorz Chwierut <grzegorz.chwierut@nordicsemi.no>

Added new field to platform specification: simulation_exec

---

src/twister2/fixtures/log_parser.py
src/twister2/log_parser/ztest_log_parser.py
tests/log_parser/ztest_log_parser_test.py

Since ingmore_fault option was introduced to yaml test definition, then it should be used instead of tags.

log_parser: use ignore_fault option

---

src/twister2/fixtures/log_parser.py
src/twister2/log_parser/__init__.py
src/twister2/log_parser/console_log_parser.py
src/twister2/log_parser/log_parser_abstract.py
src/twister2/log_parser/ztest_log_parser.py
src/twister2/yaml_test_function.py
tests/log_parser/console_log_parser_test.py
tests/log_parser/ztest_log_parser_test.py

Changes was made to make it possible to use "parse" method in more intuitive way in pure pytest tests - without calling list to iterate through generator.
Logic connected with Subtest plugin was moved to ztest_log_parser.py file.

log_parser: refactor parse method

---

requirements.txt
setup.cfg
src/twister2/builder/build_manager.py
src/twister2/builder/builder_abstract.py
src/twister2/builder/factory.py
src/twister2/builder/west_builder.py
src/twister2/fixtures/builder.py
src/twister2/fixtures/dut.py
src/twister2/fixtures/log_parser.py
src/twister2/generate_tests_plugin.py
src/twister2/helper.py
src/twister2/platform_specification.py
src/twister2/plugin.py
src/twister2/yaml_file.py
src/twister2/yaml_test_function.py
src/twister2/yaml_test_specification.py
tests/builder/build_manager_test.py
tests/builder/conftest.py
tests/builder/west_builder_test.py
tests/yaml_file_test.py
tests/yaml_test_specification_test.py

Added an implementation which allows to inject a test specification (same as for twister test) to regular pytest tests. 
Example usage:
Having test implementation like so:
```python
def test_hello_world(specification, builder, log_parser):
log_parser.parse(timeout=5)
assert log_parser.state == 'PASSED'
@pytest.mark.build_specification('scenario1', 'scenario2')
def test_hello_world_2(specification, builder, log_parser):
log_parser.parse(timeout=5)
assert log_parser.state == 'PASSED'
```
testspec.yaml:
```yaml
tests:
scenario1:
tags: introduction
timeout: 5
harness: console
harness_config:
type: one_line
regex:
- "Hello World! (.*)"
scenario2:
tags: tag1
scenario3:
tags: tag1
```
and folder structure like so:
```
├── hello_world
   ├── CMakeLists.txt
   ├── hello_world_test.py
   ├── …
```

Add specification from yaml to pytest tests

---

src/twister2/builder/west_builder.py
tests/builder/west_builder_test.py

Because all errors from `west` are redirected to `stdout` instead of `stderr` we have to log `stdout` in case of any error during building.

Improve logging for WestBuilder

---

src/twister2/quarantine_plugin.py
tests/data/quarantine/regex_example.yml
tests/twister2_plugin_quarantine_test.py

Follow some changes proposed in TwisterV1:
1. Added simulation as a filter to quarantine
2. Added regex to filter scenarios (I added regex to be allowed also in other fields: platforms, architectures and simulations),
Example quarantine file:
```
- scenarios:
- kernel.common.(misra|tls)
comment: "link to issue"
- scenarios:
- kernel.common
platforms:
- nrf53.*
- simulations:
- qemu
```

Added regex to quarantine

---

src/twister2/plugin.py

Output directory should be cleaned or renamed only in main worker/ process - not for each xdist worker/subprocess.
Without this fix, when tests are run with command:
```
pytest -vv -s --log-level=INFO -o log_cli=true --clear=archive --platform=native_posix --results-json=twister-out/results.json samples/philosophers -n 4 
```
Then 4 output directories are created (for each xdist worker) what is wrong, because all artifacts, logs and reports should be placed into one output directory.

plugin: fix bug in creating output directory

---

src/twister2/generate_tests_plugin.py
tests/twister2_plugin_test.py

This change allows to use regular tests without providing additional fixture `specification`. 
Test can be written simpler:
```python
@pytest.mark.build_specification('scenario1', 'scenario2')
def test_hello_world(log_parser):
log_parser.parse(timeout=5)
assert log_parser.state == 'PASSED'
```

Improve generating build variants (scenarios) for regular tests

---

src/twister2/builder/builder_abstract.py
src/twister2/builder/west_builder.py
src/twister2/fixtures/builder.py
src/twister2/plugin.py
src/twister2/twister_config.py
src/twister2/yaml_test_specification.py
tests/builder/conftest.py
tests/builder/west_builder_test.py
tests/twister2_plugin_test.py

`--test-item` option in `west` do not allows to parse properly `extra_configs` and `extra_args` from `.yaml` files with name different than `testcase.yaml` and `sample.yaml`. So, changes in this PR cause, that `CMake` arguments will be passed to `west` directly as additional arguments after `--` option. This will allow to handle properly `extra_configs` and `extra_args` form other `.yaml` files like `testspec.yaml`. Moreover, new argument with passing `--extra-args` from CLI was added.

Fix passing CMake extra arguments

---

src/twister2/plugin.py
src/twister2/report/helper.py
src/twister2/yaml_file.py
src/twister2/yaml_test_function.py

To keep similar names for yaml tests with regular pytest tests changing name of `YamlFile` class to `YamlModule` and `YamlTestFunction` to `YamlFunction`. After that we will have `Module` for pytest tests and `YamlModule` for twister tests, and similar for `Function` and `YamlFunction`.
Example results of running `pytest --collect-only` command:
```
<YamlModule tests/common/testcase.yaml>
<YamlFunction kernel.common[native_posix]>
<YamlFunction kernel.common.tls[native_posix]>
<YamlFunction kernel.common.misra[native_posix]>
<YamlFunction kernel.common.nano32[native_posix]>
<YamlFunction kernel.common.nano64[native_posix]>
<YamlFunction kernel.common.picolibc[native_posix]>
<Module tests/hello_world/hello_world_test.py>
<Function test_hello_world[native_posix:scenario1]>
<Function …
```

Rename yaml module and function classes

---

src/twister2/device/device_abstract.py
src/twister2/device/hardware_adapter.py
src/twister2/device/native_simulator_adapter.py

After creating separate and public method for generating flashing or running command it is necessary to add this method to abstract class.

device: add generate_command to abstract class

---

src/twister2/builder/build_manager.py
src/twister2/builder/west_builder.py
src/twister2/fixtures/builder.py
tests/builder/build_manager_test.py

This changes allow to create test scenario like:
```
@pytest.mark.build_specification
def test_upgrade(dut: DeviceAbstract, build_manager: BuildManager):
new_build_dir = str(build_manager.build_config.build_dir) + '_second_image'
build_manager.build_config.build_dir = new_build_dir
build_manager.build_config.extra_configs.append('CONFIG_MCUBOOT_IMAGE_VERSION="1.1.1+1"')
build_manager.build()
dut.generate_command(new_build_dir)
dut.flash_and_run()
```

Add build_config and builder to BuildManager

---

src/twister2/device/hardware_adapter.py
src/twister2/device/hardware_map.py
src/twister2/fixtures/builder.py
src/twister2/fixtures/common.py
src/twister2/fixtures/dut.py
src/twister2/fixtures/fixtures.py
src/twister2/fixtures/log_parser.py
src/twister2/generate_tests_plugin.py
src/twister2/plugin.py
src/twister2/report/helper.py
src/twister2/report/test_plan_plugin.py
src/twister2/report/test_results_plugin.py
src/twister2/specification_processor.py
src/twister2/twister_config.py
src/twister2/yaml_file.py
src/twister2/yaml_test_function.py
tests/fixtures/common_test.py
tests/report/report_plugin_test.py
tests/specification_processor_test.py

We need to consider separately twiser's tests and regular python tests. 
For twister's tests it is easy to run building setup and omit test body using simply `if` statement yaml test implementation.  For regular tests it is much more complicated (we don't want to force users to add additional lines to each test like:
```python
def test_foo(...):
if specification.runnably is False:
return
...
```
So the simples way to omit test execution is to mark test as skip (just after test has been built). 
Example pytest terminal report for test which are not `runnable` or `build-only` can look like that:
```
samples/hello_world/sample.yaml::sample.basic.helloworld[native_posix] <- ../twister2/src/twister2/yaml_test_function.py PASSED
tests/hello_world/hello_world_test.py::test_hello_world[native_posi …
```

Check if test is runnable base on board and specification

---

src/twister2/specification_processor.py
tests/specification_processor_test.py

Tests which depends on specific hardware elements listed in platform yaml file definition should be skipped.
Can be tested by following commands:
1. Twister v1
```
./scripts/twister -vv --inline-logs -T tests/drivers/spi/dt_spec --platform=qemu_cortex_m3 --platform=nrf52840dk_nrf52840
```
2. Twister v2
```
pytest -vv -s -o log_cli=true --clear=archive --log-level=INFO --results-json=twister-out/results.json tests/drivers/spi/dt_spec --platform=qemu_cortex_m3 --platform=nrf52840dk_nrf52840
```
In both cases only one test should be executed (built) (for `nrf52840dk_nrf52840`).
Fixes: #13

specification_processor: add depends_on filtration

---

src/twister2/specification_processor.py
src/twister2/yaml_test_specification.py

POC:
added `source_dir` to testspec.yml.
When creating new test with twisterV2, do not need to create `src` dir with sources. Only `testspec.yml` (and pytest scenarios) is required, but you must point to existing test / sample.
Example of testspec.yml:
```
common:
tags: introduction
source_dir: samples/hello_world
integration_platforms:
- native_posix
tests:
sample.basic.helloworld2:
harness: console
harness_config:
type: one_line
regex:
- "Hello World! (.*)"
kernel.fifo:
tags: kernel
source_dir: tests/kernel/fifo/fifo_api
```
Test `sample.basic.helloworld2` will use image build from `<ZEPHYR_BASE>/samples/hello_world`,
test `kernel.fifo` will use image build from `<ZEPHYR_BASE>tests/kernel/fifo/fifo_api`
`source_dir` is relative to ZEPHYR_BASE,
if ZEPHYR_BASE is …

Use source_dir in testspec.yml

---

src/twister2/device/device_abstract.py
src/twister2/device/factory.py
src/twister2/device/hardware_adapter.py
src/twister2/device/qemu_adapter.py
src/twister2/device/simulator_adapter.py
src/twister2/fixtures/common.py
tests/device/data/fifo_mock.py
tests/device/hardware_adapter_test.py
tests/device/qemu_adapter_test.py
tests/device/simulator_adapter_test.py
tests/fixtures/common_test.py

This PR implements custom simulator adapter for other simulators than zephyr. 
Tested with platform `m2gl025_miv`.
Command which was used:
```sh
pytest samples/hello_world --platform=m2gl025_miv -vvs -o log_cli=true --log-level=INFO
```
Terminal output:
```log
------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------
DEBUG    asyncio:selector_events.py:54 Using selector: EpollSelector
2023-01-17 12:47:18,542:DEBUG:twister2.device.simulator_adapter: Started subprocess with PID 43113
2023-01-17 12:47:18,642:DEBUG:twister2.log_parser.factory: Get log parser type "console"
2023-01-17 …
```

Implement custom simulator addapter

---

src/twister2/specification_processor.py
tests/data/tests/common/testcase.yaml
tests/yaml_file_test.py

Until Kconfg and DTS filtration will be not implemented then all tests with filter option in yaml test definition should be skipped.
Can be tested by:
```
pytest -vv -s --log-level=INFO -o log_cli=true --clear=archive --results-json=twister-out/results.json --platform=qemu_cortex_m3 samples/hello_world, samples/userspace/hello_world_user tests/drivers/sensor/sbs_gauge samples/arch/smp/pi 
```
Only one test should be passed:
`samples/hello_world/sample.yaml::sample.basic.helloworld[qemu_cortex_m3]`
And three next should be skipped (visible only in `twister-out/testcases_creation.log` file):
`samples/userspace/hello_world_user/sample.yaml::sample.helloworld[qemu_cortex_m3]`
`tests/drivers/sensor/sbs_gauge/testcase.yaml::drivers.sbs_gauge[qemu_cortex_m3]` …

Add temporary stub for filter option

---

src/twister2/quarantine_plugin.py

Found by @PerMac in twister V1 PR:
when there is no "Quarantine" word in the skip reason, then some features (like integration mode, parsing log output by external tools) will fail

Fix for quarantine: keep same output as is in twister v1

---

src/twister2/fixtures/common.py
tests/fixtures/common_test.py

If hardware is `mcu` type and supports run on simulator, then if device testing was not chosen, then test should be run on simulator.
For example this test should be executed on QEMU, not build-only:
```
pytest -vv -s --log-level=INFO -o log_cli=true --clear=archive --platform=mps2_an385 --results-json=twister-out/results.json samples/hello_world 
```

Add possibility to run simulation for mcu type

---

src/twister2/builder/build_manager.py
src/twister2/builder/builder_abstract.py
src/twister2/builder/west_builder.py
src/twister2/exceptions.py
src/twister2/fixtures/builder.py
src/twister2/plugin.py
src/twister2/twister_config.py
tests/builder/build_manager_test.py
tests/builder/west_builder_test.py
tests/twister2_plugin_test.py

By default if during building  memory overflow is detected, then this test should be skipped. If user uses `--overflow-as-errors` then test with overflow should be marked as failed (error).
Can be tested by:
Test should be skipped:
```
pytest -vv -s --log-level=INFO -o log_cli=true --clear=archive --platform=qemu_cortex_m3 --results-json=twister-out/results.json tests/lib/cmsis_dsp/matrix -k libraries.cmsis_dsp.matrix.unary_f64.fpu
```
Test should be marked as failed (error):
```
pytest -vv -s --log-level=INFO -o log_cli=true --clear=archive --platform=qemu_cortex_m3 --results-json=twister-out/results.json tests/lib/cmsis_dsp/matrix -k libraries.cmsis_dsp.matrix.unary_f64.fpu --overflow-as-errors
```
Fixes: #10

Detect memory overflow

---

src/twister2/plugin.py

To have similar workflow to Twister v1 the default option for "--clear" option has to be set as "archive". Thanks to this each time when twister is called new `twister-out` folder is created and previous one (if exists) is renamed.

Set archive as default option for clear option

---

src/twister2/device/qemu_adapter.py

To be more readable for potential user, the log was changed to inform that QEMU was just terminated.
Fixes: #94

qemu_adapter: change log for qemu termination

---

src/twister2/specification_processor.py
tests/specification_processor_test.py

Twister supports a special type of tests marked with type: unit. These tests require special handling as they are mocking unused modules. Those tests cannot be executed on a regular platforms. For now, such tests will be always skipped in v2.

filtration: Skip unit type tests

---

src/twister2/specification_processor.py
tests/specification_processor_test.py

To be compatible with Twister v1 supported complex features collected in platform yaml definition should be split into single one. For example:
{'netif:eth'} -> {'netif', 'eth'}
Without this mechanism it is impossible to run for example this test:
```
pytest -vvs --log-level=INFO -o log_cli=true --platform=nrf52840dk_nrf52840 --results-json=twister-out/results.json tests/net/virtual/testcase.yaml::net.virtual.tunnel.ipip 
```
Fragment of corresponding logic in Twister v1:
https://github.com/zephyrproject-rtos/zephyr/blob/48a6f160f285785d61101446930689c57468b332/scripts/pylib/twister/twisterlib/platform.py#L64-L67

specification_processor: fix depends_on filter

---

src/twister2/plugin.py
src/twister2/twister_config.py
tests/data/boards/nios2/altera_max10/altera_max10.yaml
tests/data/boards/posix/native_posix/native_posix.yaml
tests/platfrom_specification_test.py
tests/twister2_plugin_platform_selection_test.py
tests/twister2_plugin_test.py

First part, without filtering platforms with info from testcase/sample yamls 
* added --all
```
pytest samples/hello_world -vv --clear=delete --collect-only --all
527 tests collected
```
* added --emulation-only
```
pytest samples/hello_world -vv --clear=delete --collect-only --emulation-only
60 tests collected
```
* added --arch ARCH
```
pytest samples/hello_world -vv --clear=delete --collect-only --arch arm
392 tests collected
pytest samples/hello_world -vv --clear=delete --collect-only --arch nios2 --arch posix
5 tests collected
```
* take platform from hardware_map if platform not given
```
pytest samples/hello_world -vv --clear=delete --collect-only --hardware-map=map.yml
<YamlFunction sample.basic.helloworld[nrf9160dk_nrf9160_ns]>
```
Commands from twister1 to compare (interrupt …

Align selected platform - first part, without updating platform scope per testsuite

---

src/twister2/device/factory.py
src/twister2/device/simulator_adapter.py
src/twister2/fixtures/common.py
src/twister2/specification_processor.py
tests/device/simulator_adapter_test.py
tests/fixtures/common_test.py

Work as `native_posix`, but instead of `zephyr.exe` uses `testbinary` executable.
Collect tests on Twister2:
```
pytest -vv --clear=delete --testplan-json=twister-out/testplan.json --platform=unit_testing tests --collect-only
191 tests collected in 1.62s
```
On twister1:
```
scripts/twister -T tests -p unit_testing -vv -c --dry-run
grep '"platform":' twister-out/testplan.json | wc -l
192 - one is mark as skipped
```
Run tests on unit_testing platform:
```
pytest -vv --clear=delete --testplan-json=twister-out/testplan.json --platform=unit_testing tests -n 4
191 passed, 264 skipped, 1981 subtests passed in 121.59s (0:02:01)
```
Fixes: #98

Added support for unit_testing board

---

src/twister2/platform_specification.py
src/twister2/specification_processor.py
tests/specification_processor_test.py

If `BSIM_OUT_PATH` is not set, test should be skipped:
```
scripts/twister -T samples/hello_world -vv -c --dry-run -p nrf52_bsim
DEBUG   - nrf52_bsim                samples/hello_world/sample.basic.helloworld        SKIPPED: Environment (BSIM_OUT_PATH) not satisfied
```
```
pytest samples/hello_world -vv --clear=delete --collect-only --platform=nrf52_bsim
```

Add support to filter platform by environment variables

---

src/twister2/environment/environment.py
src/twister2/specification_processor.py
src/twister2/twister_config.py
tests/conftest.py
tests/report/report_plugin_test.py
tests/specification_processor_test.py
tests/twister2_plugin_quarantine_test.py

To be compatible with v1, Twister should get information about currently used toolchain and use this information during filtration process.
For example if user uses "zephyr" toolchain and platform requires "xcc" toolchain, then tests dedicated for this platform should be skipped.
For example following test should be skipped:
Twister v1
```
./scripts/twister -vv --inline-logs --platform=xt-sim -T samples/hello_world
```
Twister v2
```
pytest -vvs --log-level=INFO -o log_cli=true --platform=xt-sim samples/hello_world
```
`_get_toolchain_version_from_cmake_script` and `_run_cmake_script` were copied directly from Twister v1. It was determined with @PerMac, that at this moment we can omit refactoring and writing unit tests for those fragments.

Add used toolchain filtration 

---

src/twister2/builder/builder_abstract.py
src/twister2/log_file/build_log_file.py
src/twister2/log_file/log_file_abstract.py
tests/builder/cmake_builder_test.py
tests/builder/conftest.py
tests/builder/west_builder_test.py
tests/log_file/build_log_file_test.py

After each building Twister should store logs from this process. The PR add this functionality.

Generate build.log after building

---

src/twister2/specification_processor.py
tests/specification_processor_test.py

During toolchain filtration, `toolchain_allow` and `toolchain_exclude` should be compared with `used_toolchain_version`.
Can be tested with commands:
Twister v1:
```
scripts/twister -T tests/lib/cmsis_dsp/filtering -p native_posix -vv -c --dry-run
```
Twister v2
```
pytest tests/lib/cmsis_dsp/filtering --platform=native_posix -vv --clear=delete --testplan-json=twister-out/testplan.json --collect-only
```

Fix toolchain filtration

---

requirements-docs.txt
src/twister2/platform_specification.py
src/twister2/plugin.py
src/twister2/report/helper.py
src/twister2/specification_processor.py
src/twister2/twister_config.py
src/twister2/yaml_file.py
tests/platfrom_specification_test.py
tests/quarantine/quarantine_unit_test.py
tests/specification_processor_test.py
tests/twister2_plugin_platform_selection_test.py
tests/twister2_plugin_test.py

* integration mode added `-G, --integration` 
* second phase of selecting platform scope, getting parameters from yaml spec file (`build_on_all`, `platform_allow` etc.)
Try with commands:
```
pytest samples/hello_world -vv --clear=delete --testplan-json=twister-out/testplan.json --collect-only -G
scripts/twister -T samples/hello_world -vv -c --dry-run -G
pytest tests/bluetooth -vv --clear=delete --testplan-json=twister-out/testplan.json --collect-only
scripts/twister -T tests/bluetooth -vv -c --dry-run
pytest tests/kernel/common -vv --clear=delete --testplan-json=twister-out/testplan.json --collect-only -G --arch=posix
scripts/twister -T tests/kernel/common -vv -c --dry-run -G --arch posix
```
`build_on_all` is set in `tests/kernel/common` so all platforms are added. When using `--arch` …

Align platform scope

---

src/twister2/plugin.py
tests/filter/filter_plugin_test.py

Fixed `--enable-slow` filter option with running with xdist plugin.

Fix enable-slow tests filter for xdist

---

src/twister2/builder/build_manager.py
src/twister2/fixtures/builder.py
src/twister2/plugin.py
tests/builder/build_manager_test.py
tests/twister2_plugin_test.py

Add functionality of cleaning unecessary artifacts when test is finished. This helps a lot to reduce used memory space during running huge amount of tests.
Can be tested by:
```
pytest --platform=native_posix --runtime-artifact-cleanup=all samples/hello_world 
```
**Warning!**
--
Due to different way how arguments are parsed in Twister v2 (pytest) it is not possible to use `--runtime-artifact-cleanup` without passing `pass` or `all` parameter (like in Twister v1):
```
pytest --platform=native_posix --runtime-artifact-cleanup samples/hello_world
pytest --platform=native_posix -M samples/hello_world
```
The only safe and acceptable option is pass implicate value of parameter, like:
```
pytest --platform=native_posix --runtime-artifact-cleanup=all samples/hello_world
pytest …
```

Add runtime cleanup artifacts

---

src/twister2/log_parser/ztest_log_parser.py
src/twister2/report/test_results_plugin.py

When subtests were used, then the information about performed test was wrongly taken from first subtest. In this commit it was fixed and calculation of whole test duration (building + execution) is now set properly.
To analyze:
run Twister by command:
```
pytest --platform=native_posix tests/kernel/queue/
```
Fragment of json report **with** changes proposed in this PR:
```
"tests": [
{
"suite_name": "tests.kernel.queue.testcase.yaml",
"test_name": "kernel.queue[native_posix]",
"nodeid": "tests/kernel/queue/testcase.yaml::kernel.queue[native_posix]",
"platform": "native_posix",
...
"status": "passed",
"message": "",
"duration": 4.71,
"execution_time": 0.01,
"subtests": [
{
"name": "access_kernel_obj_with_priv_data",
"status": "passed",
"execution_time": 0.00
},
...
```
Fragment of json …

test_results: fix duration and message collection

---

src/twister2/platform_specification.py
tests/data/boards/arm/stm32f411e_disco/stm32f411e_disco.yaml
tests/data/boards/arm/stm32f411e_disco/stm32f411e_disco_B.conf
tests/data/boards/arm/stm32f411e_disco/stm32f411e_disco_D.conf
tests/platfrom_specification_test.py

Some platforms have defined revisions and Twister should recognize them as separate platforms (with @ sign in their name).
Signed-off-by: Lukasz Fundakowski <lukasz.fundakowski@nordicsemi.no>

Add support for platform revisions

---

README.rst
src/twister2/plugin.py
src/twister2/report/yaml_test_reporting_plugin.py
tests/report/report_plugin_test.py

Subtests are no longer counted towards regular tests. Especially, subtest failures are no longer added to regular failures. Unit tests were adapted accordingly.
Modify how statuses of yaml tests and subtests are reported to console. Subtests are only printed when verbosity > 1. Also, when verbosity>1, replace useless path ro yaml_test_function.py with comment telling if it was a yaml test (aka configuration) or ztestcase.

reporting: Customize reporting of yaml tests and subtests

---

requirements-tests.txt

rerunfailures and split packages are necessary during running Twister in CI, so they should be added to requirements.

requirements: add rerunfailures and split packages

---

README.rst

Add advise to turn off python tracebacks and how to handle pytest output. Expand on verbosity levels. Add how to turn on parallelization.

readme: Make readme more user friendly

---

src/twister2/twister_config.py

When twister_config is created the valuses from config are taken "as they are". This caused problems when \~ was is in zephyr_base. It was not expanded and certain modules using zephyr_base from config are failing, e.g. cmake_filter. This patch fixes the issue by expanding the path before it is added to twister_config

config: Expand \~ in zephyr_base from user args

---

src/twister2/report/helper.py
src/twister2/report/test_plan_plugin.py
src/twister2/report/test_results_plugin.py
tests/report/report_plugin_test.py

Rename tests->testsuites and subtests->testcases fields.
Add arch and run_id fields. Adapt tests.

reporting: get closer to V1 format of json report

---

src/twister2/device/hardware_map.py
src/twister2/scripts/__main__.py
src/twister2/scripts/hardware_map.py
src/twister2/twister_config.py
tests/scripts/hardware_map_test.py

Do not store every hardware-map parameter.
Fix loading empty hardware-map file.
Fix taking proper platform from loaded hardware-map file, if platform is missed in CLI.

Align hardware map generated file with twister1

---

README.rst
src/twister2/environment/environment.py
src/twister2/generate_tests_plugin.py
src/twister2/plugin.py
src/twister2/report/test_plan_plugin.py
src/twister2/report/test_results_plugin.py
src/twister2/report/yaml_test_reporting_plugin.py
src/twister2/yaml_file.py
tests/conftest.py
tests/data/pytest.ini
tests/filter/filter_plugin_test.py
tests/report/report_plugin_test.py
tests/twister2_plugin_quarantine_test.py
tests/twister2_plugin_test.py
tox.ini

To use twister one must enable it with `--twister` flag:
```
pytest --twister samples/hello_world -G --co
```
or just add it to pytest.ini file
```
[pytest]
twister = True
#addopts = --twister
```

Add --twister flag to enable plugin

---

src/twister2/device/hardware_adapter.py
src/twister2/device/hardware_map.py
src/twister2/plugin.py
src/twister2/twister_config.py
tests/device/hardware_adapter_test.py
tests/twister2_plugin_test.py

Fix #143 
Added parameters:
```
--device-serial
--device-serial-baud
--device-serial-pty
```
Functionality is ported from Twister V1.
To test / compare with Twister V1, one can use following commands:
```
./scripts/twister -vv -c -T samples/hello_world -p nrf52840dk_nrf52840 --device-testing --device-serial /dev/ttyACM0
pytest -s -v  --clear=delete samples/hello_world --device-testing  --platform=nrf52840dk_nrf52840 --device-serial=/dev/ttyACM0
```
To test `--device-serial-pty` I was created a simple script:
```
#!/usr/bin/env python3
import time
while True:
print("Hello World! AAA")
time.sleep(1)
```
and use it in comand:
```
./scripts/twister -vv -c -T samples/hello_world -p nrf52840dk_nrf52840 --device-testing --device-serial-pty $PWD/script.py
pytest -s -v  --clear=delete …
```

Port --device-serial, --device-serial-pty

---

src/twister2/device/hardware_adapter.py
src/twister2/plugin.py
src/twister2/twister_config.py
tests/device/hardware_adapter_test.py
tests/twister2_plugin_test.py

Added options:
```
--west-flash=WEST_FLASH
Extend parameters for west flash. E.g. -device-testing -west-flash="--board-
id=foobar,--erase" will translate to "west flash -- --board-id=foobar --erase"
--west-runner=WEST_RUNNER
use the specified west runner. E.g. --west-runner=pyocd
```
This is ported from TwiterV1.
`--west-flash` must have an argument (similar as with `--clear` option, if left without argument and next a folder with tests is given, than that folder name is taken as an west-flash argument). In TwisterV2 `west` is the default flash tool, so using `--west-flash` to enable using west is not required.
To test one can use following commands:
```
/scripts/twister -vv -T samples/hello_world -p nrf9160dk_nrf9160 --device-testing --device-serial /dev/ttyACM0 …
```

Port --west-flash and --west-runner options

---

src/twister2/fixtures/builder.py
src/twister2/fixtures/common.py
src/twister2/generate_tests_plugin.py
src/twister2/load_tests.py
src/twister2/plugin.py
src/twister2/specification_processor.py
src/twister2/yaml_file.py
tests/twister2_plugin_quarantine_test.py
tests/twister2_plugin_test.py

Align platform scope for regular python tests:
find changes in `GenerateTestPlugin::pytest_generate_tests`
`RegularSpecificationProcessor::get_test_configurations` is called, to select platform and scenarios.
If scenario is not selected, than item is removed in `pytest_collection_modifyitems` (do not mark as skipped for consistency with Yaml scenarios and to limit memory consumption).
`SpecificationProcessor::process` is now common for `YamlSpecificationProcessor` and `RegularSpecificationProcessor`,
`session.specifications[item.nodeid]` is updated separately for regular and yaml tests (in separate `pytest_collection_modifyitems`) to avoid mixing logic.

Changes in regular tests generation to align platform scope
