src/twister2/plugin.py
Add expansion of ~ to user's home dir.
=> args: Allow using ~ in zephyr_base path

src/twister2/builder/builder_abstract.py
=> Remove unused code from builder

.github/workflows/main.yaml, .gitignore
CI contains some deprecated actions which will be removed in future, this PR updates CI configuration to rid of these deprecated code.
=> Remove deprecated code in ci

src/twister2/builder/west.py, src/twister2/device/device_abstract.py, src/twister2/device/hardware_adapter.py, src/twister2/device/native_simulator_adapter.py, src/twister2/fixtures/dut.py, src/twister2/fixtures/log_parser.py, src/twister2/yaml_file.py, src/twister2/yaml_test_function.py, tests/device/data/mock_script.py, tests/device/hardware_adapter_test.py, tests/device/native_simulator_adapter_test.py
This PR fixes NativeSimulatorAdapter and provides some improvements for device adapters.
=> Fix native simulator adapter

src/twister2/exceptions.py, src/twister2/log_parser/console_log_parser.py, src/twister2/log_parser/factory.py, tests/log_parser/console_log_parser_test.py, tests/log_parser/data/console_log_pass.txt
This PR contains implementation for console log parser.
=> Implement console log parser

.pre-commit-config.yaml, setup.cfg, tox.ini
[pre-commit](https://pre-commit.com/) configuration was broken. This PR fixes it and also updates configuration for [isort](https://pycqa.github.io/isort/)
=> Fix pre-commit configuration

src/twister2/builder/west.py, src/twister2/device/hardware_adapter.py, src/twister2/device/native_simulator_adapter.py, src/twister2/helper.py, src/twister2/yaml_file.py, src/twister2/yaml_test_specification.py, tests/data/bluetooth/sample.yaml, tests/yaml_test_specification_test.py
Added missing fields in `YamlTestSpecification` and also added validation for data read from yaml files.
=> Add missing fields to yaml test specification

src/twister2/plugin.py, tests/twister2_plugin_test.py
Add possibility to  remove artifacts from previous run or archive
=> Cleanup twister output

src/twister2/fixtures/dut.py
If we run tests against a hardware and it is not connected/available python raises very unclear message.  Lets improve it in this PR
=> Check if hardware is available before flashing

src/twister2/plugin.py
Output directory was created first and than it was deleted in cleanup. Fixing this by changing the order.
=> Create output directory after cleanup

.github/workflows/main.yaml
Add token for codecov action to increase its stability https://discord.com/channels/@me/997097236028735578/1052495663482544139
=> workflow: Add token for codecov action

src/twister2/builder/build_manager.py, tests/builder/build_manager_test.py
`update_status` method should return `True` only when update status was really executed - when actual status is the same like this one passed to this method, then method should return `False`.
When `build_dir` variable passed to the `update_status` method was a `Path` object, then it was used directly as a key in `data` dict and it caused, that it always returned `None` status and thus the verification status didn't work properly. To solve this bug I added action to convert `build_dir` variable into `str` type at the beginning of this method.
I added also test to verify if `update_status` method works properly.
=> Fix update_status method in BuildManager

requirements-tests.txt, src/twister2/report/test_results_plugin.py, tests/conftest.py, tests/report/report_plugin_test.py, tests/twister2_plugin_test.py
=> Fix JSON report and add unit tests

README.md, src/twister2/platform_specification.py, src/twister2/scripts/__main__.py
Fixed printing default platforms.
=> Fix searching default platforms

requirements-dev.txt, requirements.txt
Added `requirements-dev.txt` with packages required for developing.
=> Added requirements for developing the code

src/twister2/plugin.py, src/twister2/report/helper.py, src/twister2/yaml_file.py
=> Fix erros rised by mypy

.pre-commit-config.yaml, src/twister2/platform_specification.py
Updated `PlatformSpecification` schema according to changes in V1.
=> Fix platform specification schema

src/twister2/generate_tests_plugin.py, src/twister2/twister_config.py, src/twister2/yaml_file.py, tests/conftest.py
To be more precisely I changed `default_platforms` into `selected_platforms`.
=> Change default_platforms to selected_platforms

src/twister2/quarantine_plugin.py, tests/twister2_plugin_quarantine_test.py
Signed-off-by: Grzegorz Chwierut <grzegorz.chwierut@nordicsemi.no>
=> Fix for loading an empty quarantine file

tox.ini
=> Add mypy check to tox.ini

.github/workflows/main.yaml, setup.cfg
Added mypy and Python 3.11 to CI. configuration.
=> Add setup for running Python 3.11 to CI

src/twister2/device/qemu_adapter.py
QEMU adapter shouldn't wait for establish fifo communication when it even didn't start. This situation can occur when QEMU is not installed and thus it cannot be started. In this case adapter should stop waiting for fifo file and raise an exception.
Can be tested only if QEMU is not installed. In my case it was for example:
```
pytest -vv -s --log-level=INFO -o log_cli=true --platform=qemu_cortex_r5 --results-json=twister-out/results.json samples/hello_world
```
=> qemu_adapter: don't wait if qemu didn't start

src/twister2/specification_processor.py
=> fix: Add TODO comment regarding unit type tests

.pre-commit-config.yaml, requirements.txt, setup.cfg, src/twister2/environment/environment.py, src/twister2/report/test_results_plugin.py, tests/report/report_plugin_test.py
This PR updates JSON report to be more compliant with V1.
=> Extend json report

README.rst, src/twister2/report/test_plan_plugin.py, src/twister2/report/test_results_plugin.py, tests/conftest.py, tests/report/report_plugin_test.py
This aligns reporting of V2 with V1
=> reports: Add twister.json as default json report

src/twister2/report/test_plan_plugin.py
The json report with results was not produced by default and it is fixed with this commit
=> bugfix: Fix json report creation
